bot:
  token: "Add your bot token here"

roulette:
  valid_bet_choices: &valid_bet_choices [ "00", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
                                          "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32",
                                          "33", "34", "35", "36", "red", "black", "even", "odd", "c1", "c2", "c3", "d1", "d2", "d3", "high",
                                          "low" ]
  black_numbers: [ 2, 4, 6, 8, 10, 11, 13, 15, 17, 20, 22, 24, 26, 28, 29, 31, 33, 35 ]
  red_numbers: [ 1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36 ]
  column1_numbers: [ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34 ]
  column2_numbers: [ 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35 ]
  column3_numbers: [ 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36 ]
  payout_values:
    straight: 35
    colour: 2
    high_low: 2
    even_odd: 2
    dozen: 3
    column: 3

leaderboard:
  valid_categories: &valid_categories [ "balance", "wins", "losses", "max_win" ]


command_text:

  help: |
    Welcome to roulette bot 
    `!me` - to create a user profile and view statistics 
    `!bet` - to create a bet. use `!bet` help to view betting options 
    `!roll` - to spin the ball and watch your money multiply 
    `!leaderboard` - to view server wide leaderboard for balance. `!leaderboard help` to view different sorting methods 
    `!beg` - to get a reload on funds when you lose all your money

  bet_help: |
    This bot supports all bets in the regular roulette games except for splitting numbers. 
    
    To create a bet follow <!bet choice1:wager_amount1 choice2:wager_amount2>
    
    For example if I want to bet $15 on red and $5 on even I would do <!bet red:15 even:5>
    
    There is no limit on the amount bets you can place, as long as you have the funds 
    
    Use `!bet clear` to cancel all current bets
    
    Valid bets include 
    [ "00", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
    "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32",
    "33", "34", "35", "36", "red", "black", "even", "odd", "c1", "c2", "c3", "d1", "d2", "d3", "high","low" ]

  leaderboard_help: |
    You can sort the server leaderboard by [ "balance", "wins", "losses", "max_win" ]
    
    !leaderboard `category` 

#  user_does_not_exist: "User does not exist yet. Please type `!me` to create a profile"
#
#  unknown_command: "Unknown command. Use `!help` for commands"